wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702014452.596913
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.11.4
      5: 0.15.4
      6: 4.29.1
      8:
      - 1
      - 5
